repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.1.6'
    hooks:
      - id: ruff
        # Respect `exclude` and `extend-exclude` settings.
        # args: ["--force-exclude", --line-length, "120"]
        args: [ "--fix", "--line-length", "120"]
      - id: ruff-format

  # - repo: https://github.com/psf/black
  #   rev: 23.7.0
  #   hooks:
  #     - id: black
  #       args: [ --line-length=120 ]

  - repo: https://github.com/myint/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
